#ifndef Pointers_h
#define Pointers_h

#include "Math.h"


    
std::map<std::string, std::string> StructureName {
{"IceBox_C", "Fridge"},
{"StorageBox_Small_C", "Small Box"},
{"StorageBox_ChemBench_C", "Chemistry Bench"},
{"MortarAndPestle_C", "Mortar Pestle"},
{"StructureTurretBaseBP_C", "Normal Turret"},
{"StructureTurretEerie_BP_C", "Eerie Turret"},//Pri
{"StorageBox_AnvilBench_C", "Smithy"},
{"ElectricGenerator_C", "Generator"},
{"StorageBox_TekGenerator_C", "Tek Generator"},
{"StorageBox_Fabricator_C", "Fabricator"},
{"SimpleBed_C", "Bed"},//
{"ElegantBed_C", "Elegant Bed"},
{"SleepingBag_C", "Sleeping Bag"},
{"StorageChest_Large_C", "Old Chest"},
{"IceBox_C", "Fridge"},
{"StorageBox_Huge_C", "Vault"},
{"StructureTurretRocket_C", "RT"},
{"TekBed_C", "Tek Bed"},
{"ModernBed_C", "Bunk Bed"},
{"BeaverDam_C", "Dam"},
{"StorageBox_Large_C", "Box"},
{"StorageBox_Small_C", "Small Box"},
{"DeathItemCache_C", "Item Cache"},
{"DroppedItemGeneric_C", "Item"},
{"StorageBox_ChemBench_C", "ChemBench"},
{"MortarAndPestle_C", "Mortar Pestle"},
{"StructureTurretBaseBP_C", "Turret"},
{"StructureTurretEerie_BP_C", "Eerie"},
{"StructureTurretPlant_C", "XPlant"},
{"Raft_BP_C", "Raft"},
{"AmberPickup_C", "Amber Rock"},
{"ResurrectionPlatform_C", "RespawnPad"}
    };
std::map<std::string, std::string> DinoName = {
{"Allo_Character_BP_C", "Allo"},
{"Ammonite_Character_BP_C", "Ammonite"},
{"Angler_Character_BP_C", "Angler"},
{"Ankylo_Character_BP_C", "Anky"},
{"SpiderS_Character_BP_C", "Araneo"},
{"Archa_Character_BP_C", "Archaeopteryx"},
{"Argent_Character_BP_C", "Argentavis"},
{"Baryonyx_Character_BP_C", "Baryonyx"},
{"Basilisk_Character_BP_C", "Basilisk"},
{"Toad_Character_BP_C", "Beelzebufo"},
{"Sauropod_Character_BP_C", "Bronto"},
{"Turtle_Character_BP_C", "Carbonemys"},
{"Carno_Character_BP_C", "Carno"},
{"Beaver_Character_BP_C", "Castoroides"},
{"Chalico_Character_BP_C", "Chalicotherium"},
{"Compy_Character_BP_C", "Compy"},
{"Dilo_Character_BP_C", "Dilophosaur"},
{"Dimetro_Character_BP_C", "Dimetrodon"},
{"Dimorph_Character_BP_C", "Dimorphodon"},
{"Diplocaulus_Character_BP_C", "Diplocaulus"},
{"Diplodocus_Character_BP_C", "Diplodocus"},
{"Direbear_Character_BP_C", "Direbear"},
{"Direwolf_Character_BP_C", "Direwolf"},
{"Dodo_Character_BP_C", "Dodo"},
{"Doed_Character_BP_C", "Doedicurus"},
{"Scarab_Character_BP_C", "Dung Beetle"},
{"Dunkle_Character_BP_C", "Dunkleosteus"},
{"Daeodon_Character_BP_C", "Daeodon"},
{"Eel_Character_BP_C", "Electrophorus"},
{"Equus_Character_BP_C", "Horse"},
{"Coel_Character_BP_C", "Coel"},
{"Anticorn_Character_BP_C", "Noctis"},
{"Galli_Character_BP_C", "Gallimimus"},
{"Gigant_Character_BP_C", "Giganotosaurus"},
{"Bigfoot_Character_BP_C", "Big Foot"},
{"Yeti_Character_BP_C", "Yeti"},
{"Griffin_Character_BP_C", "Griffin"},
{"Hesperornis_Character_BP_C", "Hesperornis"},
{"Hyaenodon_Character_BP_C", "Hyaenodon"},
{"Ichthyornis_Character_BP_C", "Ichthyornis"},
{"Ichthy_Character_BP_C", "Ichthyosaurus"},
{"Iguanodon_Character_BP_C", "Iguanodon"},
{"Jerboa_Character_BP_C", "Jerboa"},
{"Kairuku_Character_BP_C", "Kairuku"},
{"Kaprosuchus_Character_BP_C", "Kaprosuchus"},
{"Kentro_Character_BP_C", "Kentrosaurus"},
{"Crab_Character_BP_C", "Karkinos"},
{"Dolphin_Character_BP_C", "Dolphin"},
{"Lystro_Character_BP_C", "Lystro"},
{"Mammoth_Character_BP_C", "Mammoth"},
{"Manta_Character_BP_C", "Manta"},
{"Otter_Character_BP_C", "Otter"},
{"Megalania_Character_BP_C", "Megalania"},
{"Megalodon_Character_BP_C", "Megalodon"},
{"Megalosaurus_Character_BP_C", "Megalosaurus"},
{"Dragonfly_Character_BP_C", "Meganeura"},
{"Gorilla_Character_BP_C", "Megapithecus"},
{"Piranah_Character_BP_C", "Piranah"},
{"Monkey_Character_BP_C", "Mesopithecus"},
{"Microraptor_Character_BP_C", "Microraptor"},
{"Moschops_Character_BP_C", "Moschops"},
{"Mosasaur_Character_BP_C", "Mosasaurus"},
{"Bat_Character_BP_C", "Onyc"},
{"Oviraptor_Character_BP_C", "Oviraptor"},
{"Pachy_Character_BP_C", "Pachycephalosaurus"},
{"Pachyrhino_Character_BP_C", "Pachy"},
{"Para_Character_BP_C", "Parasaur"},
{"Paracer_Character_BP_C", "Paracer"},
{"Pela_Character_BP_C", "Pelagornis"},
{"Phiomia_Character_BP_C", "Phiomia"},
{"Plesiosaur_Character_BP_C", "Plesiosaur"},
{"Procoptodon_Character_BP_C", "Procoptodon"},
{"Ptero_Character_BP_C", "Pteranodon"},
{"Scorpion_Character_BP_C", "Scorpion"},
{"Quetz_Character_BP_C", "Quetzal"},
{"Raptor_Character_BP_C", "Raptor"},
{"Rex_Character_BP_C", "TRex"},
{"Saber_Character_BP_C", "Sabertooth"},
{"Sabertooth_Salmon_Character_BP_C", "Salmon"},
{"Sarco_Character_BP_C", "Sarcosuchus"},
{"Spino_Character_BP_C", "Spinosaurus"},
{"Stego_Character_BP_C", "Stego"},
{"Stag_Character_BP_C", "Deer"},
{"Tapejara_Character_BP_C", "Tapejara"},
{"Terrorbird_Character_BP_C", "Terror Bird"},
{"Therizino_Character_BP_C", "Therizino"},
{"Thylaco_Character_BP_C", "Thylacosmilus"},
{"Titanoboa_Character_BP_C", "Titanoboa"},
{"Titanomyrma_Character_BP_C", "Titanomyrma"},
{"Titanosaur_Character_BP_C", "Titanosaur"},
{"Trike_Character_BP_C", "Triceratops"},
{"Troodon_Character_BP_C", "Troodon"},
{"Tusoteuthis_Character_BP_C", "Tusoteuthis"},
{"Rhino_Character_BP_C", "Rhino"}
 };



    

#endif 
